repos:
  - repo: local
    hooks:
      - id: ruff-format
        stages: [ commit ]
        name: ruff-format
        language: system
        entry: poetry run ruff format .
        types: [ python ]
      - id: ruff-check
        stages: [ commit ]
        name: ruff-check
        language: system
        entry: poetry run ruff check . --output-format=full --fix
        types: [ python ]
      - id: gitlint
        stages: [commit-msg]
        name: gitlint
        entry: poetry run gitlint --msg-filename
        language: system
