repos:
-   repo: local
    hooks:
    - id: black
      stages: [pre-commit]
      name: black
      language: system
      entry: poetry run black
      types: [python]
    - id: isort
      stages: [pre-commit]
      name: isort
      language: system
      entry: poetry run isort
      types: [python]
    - id: flake8
      stages: [pre-commit]
      name: flake8
      language: system
      entry: poetry run flake8
      types: [python]
    - id: gitlint
      stages: [commit-msg]
      name: gitlint
      entry: poetry run gitlint --msg-filename
      language: system
