[tool.poetry]
name = "hiking"
version = "0.1.0"
description = "hiking stats"
authors = ["Fabio Ambauen <fabio@dnmx.ch>"]
readme = "README.md"
license = "MIT"
packages = [{include = "hiking"}]

[tool.poetry.dependencies]
python = "^3.10"
geopy = "^2.2.0"
gpxpy = "^1.5.0"
sqlalchemy = "^1.4.41"
plotille = "^4.0.2"
rich = "^12.5.1"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
flake8 = "^5.0.4"
flake8-bugbear = "^22.9.11"
flake8-debugger = "^4.1.2"
flake8-isort = "^4.2.0"
flake8-string-format = "^0.3.0"
flake8-tuple = "^0.4.1"
ipython = "^8.5.0"
isort = "^5.10.1"
pdbpp = "^0.10.3"
pytest = "^7.1.3"
factory-boy = "^3.2.1"
pytest-factoryboy = "^2.5.0"
pytest-env = "^0.6.2"
syrupy = "^3.0.2"
pytest-cov = "^4.0.0"
pytest-mock = "^3.9.0"

[tool.isort]
known_first_party = ["hiking"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
line_length = 88

[tool.pytest.ini_options]
env = [
    "HIKING_TEST=true",
]

[tool.coverage.run]
source = ["."]

[tool.coverage.report]
fail_under = 100
exclude_lines = [
    "pragma: no cover",
    "pragma: todo cover",
    "def __str__",
    "def __unicode__",
    "def __repr__",
]
show_missing = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
